<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  {{ stylesheet_link("css/bootstrap.min.css") }}
  {{ stylesheet_link("css/bootstrap-theme.min.css") }}
  {{ stylesheet_link("css/style.css") }}
  
  {{ javascript_include("js/jquery-1.10.1.min.js") }}
  {{ javascript_include("js/bootstrap.min.js") }}
  {{ javascript_include("js/script.js") }}
</head>
<body>
	<div class="container" style="min-width:450px;">
  	<h2>
      {{ link_to('', 'TicTacToe', 'class': 'no-decoration') }}  
    </h2>
		{% block content %} {% endblock %}
        <hr>
	</div>
</body>
</html>